
package com.bullhorn.apiservice;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bullhorn.apiservice.meta.FileMeta;
import com.bullhorn.apiservice.oauth.PartnerSessionRequest;
import com.bullhorn.apiservice.query.DtoQuery;
import com.bullhorn.apiservice.result.ApiAddFileResult;
import com.bullhorn.apiservice.result.ApiAddNoteReferenceResult;
import com.bullhorn.apiservice.result.ApiAssociateResult;
import com.bullhorn.apiservice.result.ApiDeleteFileResult;
import com.bullhorn.apiservice.result.ApiEventsCountResult;
import com.bullhorn.apiservice.result.ApiEventsGetEventsResult;
import com.bullhorn.apiservice.result.ApiEventsGetLastRequestIdResult;
import com.bullhorn.apiservice.result.ApiEventsSubscribeResult;
import com.bullhorn.apiservice.result.ApiEventsUnsubscribeResult;
import com.bullhorn.apiservice.result.ApiFindMultipleResult;
import com.bullhorn.apiservice.result.ApiFindResult;
import com.bullhorn.apiservice.result.ApiGetAssociationIdsResult;
import com.bullhorn.apiservice.result.ApiGetClientCorporationTemplateMetadataResult;
import com.bullhorn.apiservice.result.ApiGetDepartmentUserIdsResult;
import com.bullhorn.apiservice.result.ApiGetEditHistoryResult;
import com.bullhorn.apiservice.result.ApiGetEntityFieldMapsResult;
import com.bullhorn.apiservice.result.ApiGetEntityFilesResult;
import com.bullhorn.apiservice.result.ApiGetEntityMetadataResult;
import com.bullhorn.apiservice.result.ApiGetEntityNotesResult;
import com.bullhorn.apiservice.result.ApiGetEntityTemplateDataIdsResult;
import com.bullhorn.apiservice.result.ApiGetEntityTemplateDataResult;
import com.bullhorn.apiservice.result.ApiGetEntityTemplateIdsResult;
import com.bullhorn.apiservice.result.ApiGetFileResult;
import com.bullhorn.apiservice.result.ApiGetJobOrderTemplateMetadataResult;
import com.bullhorn.apiservice.result.ApiGetNoteReferencesResult;
import com.bullhorn.apiservice.result.ApiGetUserDepartmentIdsResult;
import com.bullhorn.apiservice.result.ApiGetUserPrimaryDepartmentIdResult;
import com.bullhorn.apiservice.result.ApiGetUserTemplateMetadataResult;
import com.bullhorn.apiservice.result.ApiGetUserTypesResult;
import com.bullhorn.apiservice.result.ApiGetViewLayoutResult;
import com.bullhorn.apiservice.result.ApiParseResumeResult;
import com.bullhorn.apiservice.result.ApiQueryResult;
import com.bullhorn.apiservice.result.ApiRemoveNoteReferenceResult;
import com.bullhorn.apiservice.result.ApiResult;
import com.bullhorn.apiservice.result.ApiSaveResult;
import com.bullhorn.apiservice.result.ApiStartSessionResult;
import com.bullhorn.apiservice.result.ApiUnassociateResult;
import com.bullhorn.apiservice.result.ApiUpdateFileResult;
import com.bullhorn.dataevent.subscription.SubscriptionCriteria;
import com.bullhorn.entity.AbstractDto;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ApiService", targetNamespace = "http://apiservice.bullhorn.com/")
@XmlSeeAlso({
    com.bullhorn.entity.template.job.ObjectFactory.class,
    com.bullhorn.apiservice.query.ObjectFactory.class,
    com.bullhorn.entity.userwork.ObjectFactory.class,
    com.bullhorn.entity.invoice.ObjectFactory.class,
    com.bullhorn.entity.privatelabel.ObjectFactory.class,
    com.bullhorn.entity.ObjectFactory.class,
    com.bullhorn.entity.lists.ObjectFactory.class,
    com.bullhorn.apiservice.ObjectFactory.class,
    com.bullhorn.entity.housing.ObjectFactory.class,
    com.bullhorn.apiservice.struct.ObjectFactory.class,
    com.bullhorn.entity.note.ObjectFactory.class,
    com.bullhorn.apiservice.oauth.ObjectFactory.class,
    com.bullhorn.apiservice.result.ObjectFactory.class,
    com.bullhorn.entity.user.ObjectFactory.class,
    com.bullhorn.entity.survey.ObjectFactory.class,
    com.bullhorn.dataevent.subscription.ObjectFactory.class,
    com.bullhorn.entity.emb.ObjectFactory.class,
    com.bullhorn.entity.tearsheet.ObjectFactory.class,
    com.bullhorn.entity.appointment.ObjectFactory.class,
    com.bullhorn.entity.template.user.ObjectFactory.class,
    com.bullhorn.entity.cert.ObjectFactory.class,
    com.bullhorn.entity.ratecard.ObjectFactory.class,
    com.bullhorn.entity.distlist.ObjectFactory.class,
    com.bullhorn.entity.job.ObjectFactory.class,
    com.bullhorn.entity.timecard.ObjectFactory.class,
    com.bullhorn.entity.types.ObjectFactory.class,
    com.bullhorn.entity.report.ObjectFactory.class,
    com.bullhorn.dataevent.event.ObjectFactory.class,
    com.bullhorn.apiservice.meta.ObjectFactory.class,
    com.bullhorn.entity.corp.ObjectFactory.class,
    com.bullhorn.entity.test.ObjectFactory.class,
    com.bullhorn.apiservice.edithistory.ObjectFactory.class,
    com.bullhorn.entity.task.ObjectFactory.class,
    com.bullhorn.entity.client.ObjectFactory.class,
    com.bullhorn.entity.template.client.ObjectFactory.class,
    com.bullhorn.entity.template.ObjectFactory.class,
    com.bullhorn.entity.candidate.ObjectFactory.class,
    com.bullhorn.dataevent.result.ObjectFactory.class
})
public interface ApiService {


    /**
     * 
     * @param fileId
     * @param session
     * @param entityId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetFileResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFile", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetFile")
    @ResponseWrapper(localName = "getFileResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetFileResponse")
    public ApiGetFileResult getFile(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId,
        @WebParam(name = "fileId", targetNamespace = "")
        Object fileId);

    /**
     * 
     * @param criteria
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsSubscribeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsSubscribe", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsSubscribe")
    @ResponseWrapper(localName = "eventsSubscribeResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsSubscribeResponse")
    public ApiEventsSubscribeResult eventsSubscribe(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "criteria", targetNamespace = "")
        SubscriptionCriteria criteria);

    /**
     * 
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsUnsubscribeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsUnsubscribe", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsUnsubscribe")
    @ResponseWrapper(localName = "eventsUnsubscribeResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsUnsubscribeResponse")
    public ApiEventsUnsubscribeResult eventsUnsubscribe(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId);

    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityNotesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityNotes", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotes")
    @ResponseWrapper(localName = "getEntityNotesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotesResponse")
    public ApiGetEntityNotesResult getEntityNotes(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @param notesWhere
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityNotesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityNotesWhere", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotesWhere")
    @ResponseWrapper(localName = "getEntityNotesWhereResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityNotesWhereResponse")
    public ApiGetEntityNotesResult getEntityNotesWhere(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "notesWhere", targetNamespace = "")
        String notesWhere);

    /**
     * 
     * @param session
     * @param noteId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetNoteReferencesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNoteReferences", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetNoteReferences")
    @ResponseWrapper(localName = "getNoteReferencesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetNoteReferencesResponse")
    public ApiGetNoteReferencesResult getNoteReferences(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "noteId", targetNamespace = "")
        int noteId);

    /**
     * 
     * @param session
     * @param entityId
     * @param noteId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAddNoteReferenceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addNoteReference", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AddNoteReference")
    @ResponseWrapper(localName = "addNoteReferenceResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AddNoteReferenceResponse")
    public ApiAddNoteReferenceResult addNoteReference(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "noteId", targetNamespace = "")
        int noteId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        int entityId);

    /**
     * 
     * @param session
     * @param entityId
     * @param noteId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiRemoveNoteReferenceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeNoteReference", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.RemoveNoteReference")
    @ResponseWrapper(localName = "removeNoteReferenceResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.RemoveNoteReferenceResponse")
    public ApiRemoveNoteReferenceResult removeNoteReference(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "noteId", targetNamespace = "")
        int noteId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        int entityId);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityMetadata")
    @ResponseWrapper(localName = "getEntityMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityMetadataResponse")
    public ApiGetEntityMetadataResult getEntityMetadata(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @param typeId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderMetadata")
    @ResponseWrapper(localName = "getJobOrderMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderMetadataResponse")
    public ApiGetEntityMetadataResult getJobOrderMetadata(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "typeId", targetNamespace = "")
        int typeId,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param count
     * @param session
     * @param subscriptionId
     * @param entityName
     */
    @WebMethod(operationName = "_eventsGenerateBogusEvents")
    @RequestWrapper(localName = "_eventsGenerateBogusEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusEvents")
    @ResponseWrapper(localName = "_eventsGenerateBogusEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusEventsResponse")
    public void eventsGenerateBogusEvents(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @param count
     * @param session
     * @param subscriptionId
     */
    @WebMethod(operationName = "_eventsGenerateBogusJobMatchSearchEvents")
    @RequestWrapper(localName = "_eventsGenerateBogusJobMatchSearchEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusJobMatchSearchEvents")
    @ResponseWrapper(localName = "_eventsGenerateBogusJobMatchSearchEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusJobMatchSearchEventsResponse")
    public void eventsGenerateBogusJobMatchSearchEvents(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @param count
     * @param session
     * @param subscriptionId
     */
    @WebMethod(operationName = "_eventsGenerateBogusFieldMapChangeEvents")
    @RequestWrapper(localName = "_eventsGenerateBogusFieldMapChangeEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusFieldMapChangeEvents")
    @ResponseWrapper(localName = "_eventsGenerateBogusFieldMapChangeEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGenerateBogusFieldMapChangeEventsResponse")
    public void eventsGenerateBogusFieldMapChangeEvents(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "count", targetNamespace = "")
        int count);

    /**
     * 
     * @param maxEvents
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsGetEventsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsGetEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetEvents")
    @ResponseWrapper(localName = "eventsGetEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetEventsResponse")
    public ApiEventsGetEventsResult eventsGetEvents(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "maxEvents", targetNamespace = "")
        int maxEvents);

    /**
     * 
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsGetLastRequestIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsGetLastRequestId", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetLastRequestId")
    @ResponseWrapper(localName = "eventsGetLastRequestIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsGetLastRequestIdResponse")
    public ApiEventsGetLastRequestIdResult eventsGetLastRequestId(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId);

    /**
     * 
     * @param requestId
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsGetEventsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsRegetEvents", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsRegetEvents")
    @ResponseWrapper(localName = "eventsRegetEventsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsRegetEventsResponse")
    public ApiEventsGetEventsResult eventsRegetEvents(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId,
        @WebParam(name = "requestId", targetNamespace = "")
        long requestId);

    /**
     * 
     * @param username
     * @param source
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getApplicationServerHost", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetApplicationServerHost")
    @ResponseWrapper(localName = "getApplicationServerHostResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetApplicationServerHostResponse")
    public String getApplicationServerHost(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "source", targetNamespace = "")
        String source);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiQueryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCertifications", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetCertifications")
    @ResponseWrapper(localName = "getCertificationsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetCertificationsResponse")
    public ApiQueryResult getCertifications(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param session
     * @param entityId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityFilesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityFiles", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityFiles")
    @ResponseWrapper(localName = "getEntityFilesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityFilesResponse")
    public ApiGetEntityFilesResult getEntityFiles(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId);

    /**
     * 
     * @param fileMetaData
     * @param session
     * @param entityId
     * @param fileContent
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAddFileResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFile", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AddFile")
    @ResponseWrapper(localName = "addFileResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AddFileResponse")
    public ApiAddFileResult addFile(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId,
        @WebParam(name = "fileMetaData", targetNamespace = "")
        FileMeta fileMetaData,
        @WebParam(name = "fileContent", targetNamespace = "")
        DataHandler fileContent);

    /**
     * 
     * @param fileId
     * @param fileMetaData
     * @param session
     * @param entityId
     * @param fileContent
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiUpdateFileResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateFile", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UpdateFile")
    @ResponseWrapper(localName = "updateFileResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UpdateFileResponse")
    public ApiUpdateFileResult updateFile(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId,
        @WebParam(name = "fileMetaData", targetNamespace = "")
        FileMeta fileMetaData,
        @WebParam(name = "fileId", targetNamespace = "")
        Object fileId,
        @WebParam(name = "fileContent", targetNamespace = "")
        DataHandler fileContent);

    /**
     * 
     * @param fileId
     * @param session
     * @param entityId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiDeleteFileResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteFile", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteFile")
    @ResponseWrapper(localName = "deleteFileResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteFileResponse")
    public ApiDeleteFileResult deleteFile(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "entityId", targetNamespace = "")
        Object entityId,
        @WebParam(name = "fileId", targetNamespace = "")
        Object fileId);

    /**
     * 
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderTemplateIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateIds")
    @ResponseWrapper(localName = "getJobOrderTemplateIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateIdsResponse")
    public ApiGetEntityTemplateIdsResult getJobOrderTemplateIds(
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param templateId
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetJobOrderTemplateMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderTemplateMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateMetadata")
    @ResponseWrapper(localName = "getJobOrderTemplateMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateMetadataResponse")
    public ApiGetJobOrderTemplateMetadataResult getJobOrderTemplateMetadata(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId);

    /**
     * 
     * @param templateId
     * @param session
     * @param jobOrderId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateDataIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderTemplateDataIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateDataIds")
    @ResponseWrapper(localName = "getJobOrderTemplateDataIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateDataIdsResponse")
    public ApiGetEntityTemplateDataIdsResult getJobOrderTemplateDataIds(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId,
        @WebParam(name = "jobOrderId", targetNamespace = "")
        int jobOrderId);

    /**
     * 
     * @param templateId
     * @param session
     * @param dataId
     * @param jobOrderId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateDataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderTemplateData", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateData")
    @ResponseWrapper(localName = "getJobOrderTemplateDataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderTemplateDataResponse")
    public ApiGetEntityTemplateDataResult getJobOrderTemplateData(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId,
        @WebParam(name = "jobOrderId", targetNamespace = "")
        int jobOrderId,
        @WebParam(name = "dataId", targetNamespace = "")
        int dataId);

    /**
     * 
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserTemplateIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateIds")
    @ResponseWrapper(localName = "getUserTemplateIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateIdsResponse")
    public ApiGetEntityTemplateIdsResult getUserTemplateIds(
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param templateId
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserTemplateMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserTemplateMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateMetadata")
    @ResponseWrapper(localName = "getUserTemplateMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateMetadataResponse")
    public ApiGetUserTemplateMetadataResult getUserTemplateMetadata(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId);

    /**
     * 
     * @param templateId
     * @param session
     * @param userId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateDataIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserTemplateDataIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateDataIds")
    @ResponseWrapper(localName = "getUserTemplateDataIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateDataIdsResponse")
    public ApiGetEntityTemplateDataIdsResult getUserTemplateDataIds(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId,
        @WebParam(name = "userId", targetNamespace = "")
        int userId);

    /**
     * 
     * @param templateId
     * @param session
     * @param dataId
     * @param userId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateDataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserTemplateData", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateData")
    @ResponseWrapper(localName = "getUserTemplateDataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTemplateDataResponse")
    public ApiGetEntityTemplateDataResult getUserTemplateData(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId,
        @WebParam(name = "userId", targetNamespace = "")
        int userId,
        @WebParam(name = "dataId", targetNamespace = "")
        int dataId);

    /**
     * 
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientCorporationTemplateIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateIds")
    @ResponseWrapper(localName = "getClientCorporationTemplateIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateIdsResponse")
    public ApiGetEntityTemplateIdsResult getClientCorporationTemplateIds(
        @WebParam(name = "session", targetNamespace = "")
        String session);

    /**
     * 
     * @param templateId
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetClientCorporationTemplateMetadataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientCorporationTemplateMetadata", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateMetadata")
    @ResponseWrapper(localName = "getClientCorporationTemplateMetadataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateMetadataResponse")
    public ApiGetClientCorporationTemplateMetadataResult getClientCorporationTemplateMetadata(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId);

    /**
     * 
     * @param templateId
     * @param session
     * @param clientCorporationId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateDataIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientCorporationTemplateDataIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateDataIds")
    @ResponseWrapper(localName = "getClientCorporationTemplateDataIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateDataIdsResponse")
    public ApiGetEntityTemplateDataIdsResult getClientCorporationTemplateDataIds(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId,
        @WebParam(name = "clientCorporationId", targetNamespace = "")
        int clientCorporationId);

    /**
     * 
     * @param templateId
     * @param session
     * @param dataId
     * @param clientCorporationId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityTemplateDataResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClientCorporationTemplateData", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateData")
    @ResponseWrapper(localName = "getClientCorporationTemplateDataResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetClientCorporationTemplateDataResponse")
    public ApiGetEntityTemplateDataResult getClientCorporationTemplateData(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "templateId", targetNamespace = "")
        int templateId,
        @WebParam(name = "clientCorporationId", targetNamespace = "")
        int clientCorporationId,
        @WebParam(name = "dataId", targetNamespace = "")
        int dataId);

    /**
     * 
     * @param session
     * @param base64ChunkedResume
     * @return
     *     returns com.bullhorn.apiservice.result.ApiParseResumeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "parseResume", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.ParseResume")
    @ResponseWrapper(localName = "parseResumeResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.ParseResumeResponse")
    public ApiParseResumeResult parseResume(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "base64ChunkedResume", targetNamespace = "")
        byte[] base64ChunkedResume);

    /**
     * 
     * @param session
     * @param subscriptionId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiEventsCountResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eventsCount", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsCount")
    @ResponseWrapper(localName = "eventsCountResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.EventsCountResponse")
    public ApiEventsCountResult eventsCount(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "subscriptionId", targetNamespace = "")
        String subscriptionId);

    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEditHistoryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEditHistory", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEditHistory")
    @ResponseWrapper(localName = "getEditHistoryResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEditHistoryResponse")
    public ApiGetEditHistoryResult getEditHistory(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param id
     * @param transactionId
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEditHistoryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEditHistoryByTransactionId", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEditHistoryByTransactionId")
    @ResponseWrapper(localName = "getEditHistoryByTransactionIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEditHistoryByTransactionIdResponse")
    public ApiGetEditHistoryResult getEditHistoryByTransactionId(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "transactionId", targetNamespace = "")
        String transactionId);

    /**
     * 
     * @param id
     * @param startDate
     * @param session
     * @param endDate
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEditHistoryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEditHistoryByDates", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEditHistoryByDates")
    @ResponseWrapper(localName = "getEditHistoryByDatesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEditHistoryByDatesResponse")
    public ApiGetEditHistoryResult getEditHistoryByDates(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "startDate", targetNamespace = "")
        XMLGregorianCalendar startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        XMLGregorianCalendar endDate);

    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiFindResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindResponse")
    public ApiFindResult find(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param dto
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiSaveResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.SaveResponse")
    public ApiSaveResult save(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "dto", targetNamespace = "")
        AbstractDto dto);

    /**
     * 
     * @param dto
     * @param session
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteResponse")
    public ApiResult delete(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "dto", targetNamespace = "")
        AbstractDto dto);

    /**
     * 
     * @param session
     * @param query
     * @return
     *     returns com.bullhorn.apiservice.result.ApiQueryResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.QueryResponse")
    public ApiQueryResult query(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "query", targetNamespace = "")
        DtoQuery query);

    /**
     * 
     * @param id
     * @param associateId
     * @param associationName
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAssociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "associate", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Associate")
    @ResponseWrapper(localName = "associateResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AssociateResponse")
    public ApiAssociateResult associate(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateId", targetNamespace = "")
        Object associateId);

    /**
     * 
     * @param session
     * @param ids
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiFindMultipleResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findMultiple", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindMultiple")
    @ResponseWrapper(localName = "findMultipleResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.FindMultipleResponse")
    public ApiFindMultipleResult findMultiple(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "ids", targetNamespace = "")
        List<Object> ids);

    /**
     * 
     * @param id
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteById", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteById")
    @ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.DeleteByIdResponse")
    public ApiResult deleteById(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id);

    /**
     * 
     * @param id
     * @param associationName
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetAssociationIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAssociationIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetAssociationIds")
    @ResponseWrapper(localName = "getAssociationIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetAssociationIdsResponse")
    public ApiGetAssociationIdsResult getAssociationIds(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName);

    /**
     * 
     * @param id
     * @param associationName
     * @param session
     * @param associateIds
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiAssociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "associateMultiple", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AssociateMultiple")
    @ResponseWrapper(localName = "associateMultipleResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.AssociateMultipleResponse")
    public ApiAssociateResult associateMultiple(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateIds", targetNamespace = "")
        List<Object> associateIds);

    /**
     * 
     * @param id
     * @param associateId
     * @param associationName
     * @param session
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiUnassociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassociate", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.Unassociate")
    @ResponseWrapper(localName = "unassociateResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UnassociateResponse")
    public ApiUnassociateResult unassociate(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateId", targetNamespace = "")
        Object associateId);

    /**
     * 
     * @param id
     * @param associationName
     * @param session
     * @param associateIds
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiUnassociateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unassociateMultiple", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UnassociateMultiple")
    @ResponseWrapper(localName = "unassociateMultipleResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.UnassociateMultipleResponse")
    public ApiUnassociateResult unassociateMultiple(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "id", targetNamespace = "")
        Object id,
        @WebParam(name = "associationName", targetNamespace = "")
        String associationName,
        @WebParam(name = "associateIds", targetNamespace = "")
        List<Object> associateIds);

    /**
     * 
     * @param session
     * @param departmentId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetDepartmentUserIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDepartmentUserIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetDepartmentUserIds")
    @ResponseWrapper(localName = "getDepartmentUserIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetDepartmentUserIdsResponse")
    public ApiGetDepartmentUserIdsResult getDepartmentUserIds(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "departmentId", targetNamespace = "")
        int departmentId);

    /**
     * 
     * @param session
     * @param corporateUserId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserDepartmentIdsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDepartmentIds", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserDepartmentIds")
    @ResponseWrapper(localName = "getUserDepartmentIdsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserDepartmentIdsResponse")
    public ApiGetUserDepartmentIdsResult getUserDepartmentIds(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "corporateUserId", targetNamespace = "")
        int corporateUserId);

    /**
     * 
     * @param session
     * @param corporateUserId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserPrimaryDepartmentIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserPrimaryDepartmentId", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserPrimaryDepartmentId")
    @ResponseWrapper(localName = "getUserPrimaryDepartmentIdResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserPrimaryDepartmentIdResponse")
    public ApiGetUserPrimaryDepartmentIdResult getUserPrimaryDepartmentId(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "corporateUserId", targetNamespace = "")
        int corporateUserId);

    /**
     * 
     * @param session
     * @param personEntityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetUserTypesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserTypes", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTypes")
    @ResponseWrapper(localName = "getUserTypesResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetUserTypesResponse")
    public ApiGetUserTypesResult getUserTypes(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "personEntityName", targetNamespace = "")
        String personEntityName);

    /**
     * 
     * @param arg0
     */
    @WebMethod(operationName = "_exportApiEnums")
    @RequestWrapper(localName = "_exportApiEnums", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.ExportApiEnums")
    @ResponseWrapper(localName = "_exportApiEnumsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.ExportApiEnumsResponse")
    public void exportApiEnums(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityFieldMapsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEntityFieldMaps", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityFieldMaps")
    @ResponseWrapper(localName = "getEntityFieldMapsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetEntityFieldMapsResponse")
    public ApiGetEntityFieldMapsResult getEntityFieldMaps(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param session
     * @param privateLabelId
     * @param typeId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetEntityFieldMapsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderFieldMaps", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderFieldMaps")
    @ResponseWrapper(localName = "getJobOrderFieldMapsResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderFieldMapsResponse")
    public ApiGetEntityFieldMapsResult getJobOrderFieldMaps(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "typeId", targetNamespace = "")
        int typeId,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param session
     * @param sectionName
     * @param privateLabelId
     * @param entityName
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetViewLayoutResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getViewLayout", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetViewLayout")
    @ResponseWrapper(localName = "getViewLayoutResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetViewLayoutResponse")
    public ApiGetViewLayoutResult getViewLayout(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "sectionName", targetNamespace = "")
        String sectionName,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param session
     * @param sectionName
     * @param privateLabelId
     * @param typeId
     * @return
     *     returns com.bullhorn.apiservice.result.ApiGetViewLayoutResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobOrderViewLayout", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderViewLayout")
    @ResponseWrapper(localName = "getJobOrderViewLayoutResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.GetJobOrderViewLayoutResponse")
    public ApiGetViewLayoutResult getJobOrderViewLayout(
        @WebParam(name = "session", targetNamespace = "")
        String session,
        @WebParam(name = "typeId", targetNamespace = "")
        int typeId,
        @WebParam(name = "sectionName", targetNamespace = "")
        String sectionName,
        @WebParam(name = "privateLabelId", targetNamespace = "")
        Integer privateLabelId);

    /**
     * 
     * @param username
     * @param password
     * @param apiKey
     * @return
     *     returns com.bullhorn.apiservice.result.ApiStartSessionResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startSession", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.StartSession")
    @ResponseWrapper(localName = "startSessionResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.StartSessionResponse")
    public ApiStartSessionResult startSession(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "apiKey", targetNamespace = "")
        String apiKey);

    /**
     * 
     * @param sessionRequest
     * @return
     *     returns com.bullhorn.apiservice.result.ApiStartSessionResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "startPartnerSession", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.StartPartnerSession")
    @ResponseWrapper(localName = "startPartnerSessionResponse", targetNamespace = "http://apiservice.bullhorn.com/", className = "com.bullhorn.apiservice.StartPartnerSessionResponse")
    public ApiStartSessionResult startPartnerSession(
        @WebParam(name = "sessionRequest", targetNamespace = "")
        PartnerSessionRequest sessionRequest);

}
